env:
  node: true
  es2021: true
extends:
  - airbnb-base
  - plugin:import/typescript
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
  ecmaVersion: 2023
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  import/extensions: ['error', 'ignorePackages', {'ts': 'never', 'tsx': 'never'}]
  max-len: [error, { code: 120, ignoreStrings: true, ignoreTemplateLiterals: true, ignoreComments: true }]
